title: "[Idea] "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! Please describe your feature request below.

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which CLI platform does this apply to?
      options:
        - All platforms
        - Claude Code
        - Codex CLI
        - Gemini CLI
        - Ollama CLI (planned)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or improved?
      placeholder: Describe your idea...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this help your workflow?
      placeholder: Explain the problem this would solve...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you tried any workarounds?
      placeholder: Describe any alternatives you've considered...
    validations:
      required: false
